tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "error-dim": "#fca5a5",
                "outline": "#6882a5",
                "on-tertiary-container": "#fef3c7",
                "on-tertiary": "#1c1917",
                "secondary-container": "#243246",
                "on-error": "#1f2937",
                "error": "#f87171",
                "surface-bright": "#132238",
                "inverse-on-surface": "#0b1220",
                "on-error-container": "#fee2e2",
                "primary-dim": "#7aa6ff",
                "surface-container-low": "#111f2f",
                "outline-variant": "#334867",
                "on-primary": "#031526",
                "tertiary-dim": "#fbbf24",
                "secondary": "#afc4e8",
                "on-surface": "#edf5ff",
                "secondary-fixed-dim": "#364b68",
                "secondary-dim": "#a5b9d9",
                "on-tertiary-fixed-variant": "#fff7ed",
                "surface-container-lowest": "#0a1320",
                "on-secondary": "#0a1220",
                "tertiary": "#f8b63b",
                "surface-variant": "#152844",
                "inverse-surface": "#edf5ff",
                "on-primary-fixed-variant": "#dfeaff",
                "on-secondary-fixed-variant": "#dbeafe",
                "primary-container": "#7aa6ff",
                "on-tertiary-fixed": "#1f1608",
                "surface-container-highest": "#1d3352",
                "primary-fixed": "#a7c3ff",
                "on-background": "#edf5ff",
                "tertiary-fixed": "#fbbf24",
                "surface-dim": "#0b1422",
                "inverse-primary": "#08307a",
                "surface": "#0b1320",
                "surface-tint": "#7aa6ff",
                "secondary-fixed": "#223752",
                "error-container": "#7f1d1d",
                "primary-fixed-dim": "#6d9cff",
                "on-secondary-container": "#dfeaff",
                "on-secondary-fixed": "#dfeaff",
                "primary": "#7aa6ff",
                "background": "#071521",
                "tertiary-container": "#fbbf24",
                "surface-container-high": "#162b40",
                "on-primary-container": "#dfeaff",
                "surface-container": "#132238",
                "on-primary-fixed": "#031526",
                "on-surface-variant": "#b7c8df",
                "tertiary-fixed-dim": "#f59e0b"
            },
            fontFamily: {
                "headline": ["Epilogue"],
                "body": ["Manrope"],
                "label": ["Plus Jakarta Sans"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"}
        }
    }
};
